### ISSUE TITLE
[Suggestion] Any time frame on the server files? (Me and My friends are trying to set one up)

### ISSUE THREAD

**Issue by GlitchSlayed** [TCreopargh/GreedyCraft#114]
Me and my friends are just waiting for the server files as its is taking us to long to remove the client side mods and set stuff up (my friend is pretty new at this)

**Comment by TCreopargh** [comment]
server files will be made when the pack is more stable. Right now you can follow the guide on GitHub wiki to make a server pack yourself.

**Comment by jehseuss** [comment]
New plan! Use the ignoreProject option in ServerStarter and get down to two files needed to start a server, easy-peasy. New steps are:

1. Grab ATM's start script [here](https://gist.github.com/jehseuss/1312e3d6dac125b06835b86dd126275a). chmod +x this. I did not modify this in the slightest, it's just a copy paste from ATM3. You might need to change or dump the `#1/usr/bin/sh` at line 1; my distro did not care for that.

2. Go snag my new and improved `server-setup-config.yaml` [config file](https://gist.github.com/jehseuss/cf42f2b886e9a7bb46cae4d05b85fe42)and copy is contents to your own server. Run ./start.sh and it should 'just work*'.

Keep in mind this is a first pass - I just spent an hour trying to find the project ID for each client side mod in that Python script and I'm sure I missed a few. Consider it a proof of concept.

* When being asked which world gen I wanted ServerStarter got hung up and I had to kill it and re-run, but this is almost guaranteedly due to the fact I'm testing this on a box with 16GB of memory running modded Ark and Valheim...it's a bit cramped...

Older, less awesome stuff left below for reference...

> I just had to do this and generally don't work with packs that don't supply server files and as such had to learn. I've got a pretty simple setup now that you can take a swing at that I stole from ATM3:
> 
> 1. Create a file on your server called server-setup-config.yaml and dump [this ](https://gist.github.com/jehseuss/db6ee4105a05466aa1d3fc53b1245126) into it. This file is used by [ServerStarter ](https://github.com/BloodyMods/ServerStarter) which looks like something the ATM team created to act as a spec for setting up servers. There isn't a ton of documentation but it mostly just works. There is also a section in there called ignoredFiles which I *hoped* would ignore all the client side mods and not install them. Sadly, it didn't work, but I left it there for people to tinker with. There's a place to ignore mods by ID too, so that might be the solution.
> 
> 2. Grab ATM's start script [here](https://gist.github.com/jehseuss/1312e3d6dac125b06835b86dd126275a). chmod +x this. I did not modify this in the slightest, it's just a copy paste from ATM3. You might need to change or dump the `#1/usr/bin/sh` at line 1; my distro did not care for that.
> 
> 3. ./start.sh and wait. ServerStarter will go download all the mods for you, grab the right forge version based on the modpack, and prompt you for the EULA + later on the level-type. **This will fail the first launch as we have client-side mod installed!**. Once it starts throwing exceptions, ctrl-c out of it and we're on to the next step.
> 
> 4. Now the important bit: go grab this Python [script](https://github.com/Lgk2/DeleteClientMods/blob/main/Delete%20Client%20Mods.py) which some very nice person created and drop it in your mod folder and run it. All it does is delete the client-side mods that will cause crashing. Or delete them manually. You do you! 
> 
> 5. ./start.sh again. It will ask if you want to redownload but that shouldn't matter. At this point (after waiting a bit!) I was able to successfully launch.
> 
> If you're on Windows, go over and grab ATM3's server files and you should find a .bat file there that's pretty much the same. You just need to edit it to use the correct forge version and modpack URL and delete the client-side mods.
> 
> **Edit**: Note that I am also still using ATM's Java args in that yaml file - not sure if that will cause issues so you might want to change those.

**Comment by TCreopargh** [comment]
Thanks for providing that, i'll make a server pack once this modpack is stable enough. Right now there are frequent updates and it's hard to maintain a lot of versions.

**Comment by kunwon1** [comment]
Some additions - 

> When being asked which world gen I wanted ServerStarter got hung up and I had to kill it and re-run, but this is almost guaranteedly due to the fact I'm testing this on a box with 16GB of memory running modded Ark and Valheim...it's a bit cramped...

This happened to me too, on a box with A LOT of resources not running anything else. You should see it ask you for world type, then you should see the angle bracket on a line by itself '>' - if no angle bracket, it's hung. ctrl+c and start again.

You MAY be able to bypass that by creating server.properties before running start.sh, and adding this line (for default BoP world type):

> defaultworldgenerator-port=98f16d23-cbcb-11ea-ac7b-005056c00008

I haven't tested this

Line 26 of server-setup-config.yaml, change the url to 'https://media.forgecdn.net/files/3206/235/GreedyCraft-1.32.0.111.1.zip' for the latest version of the pack

**Comment by TCreopargh** [comment]
Server pack is up
