### ISSUE TITLE
进入游戏之后走了几步游戏就崩了

### ISSUE THREAD

**Issue by CreazyDave** [TCreopargh/GreedyCraft#240]
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash reports or logs**
If the problem causes a crash, please paste your crash report to a online pastebin like [Ubuntu Paste](https://paste.ubuntu.com/) and copy the link after pasting and paste it here. Crash report can be found in your `crash-reports` folder located in your Minecraft instance folder.
Latest log can be found in `latest.log` file in your `logs` folder.

**Details**
Please fill out the blanks below:
Modpack Version: (  )
Did you add or remove mods? (  )
Did you edit any config or script? (  )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (  )
Singleplayer, LAN game or server pack? (  )

**Additional context**
[minecraft-exported-logs-2021-12-30T13-01-04.log](https://github.com/TCreopargh/GreedyCraft/files/7791549/minecraft-exported-logs-2021-12-30T13-01-04.log)

**Comment by ryuujo1573** [comment]
# An error report file with more information is saved as:
# D:\.mc\.贪婪\.minecraft\versions\GreedyCraft\hs_err_pid26600.log
请：

On Dec 30, 2021, at 13:01, CreazyDave ***@***.******@***.***>> wrote:



Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue.
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.

  *    Yes, I'm sure this problem isn't because my game ran out of RAM.

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

  1.  Go to '...'
  2.  Click on '....'
  3.  Scroll down to '....'
  4.  See error

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Crash reports or logs
If the problem causes a crash, please paste your crash report to a online pastebin like Ubuntu Paste<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpaste.ubuntu.com%2F&data=04%7C01%7C%7Ca874096209434d26527608d9cb51747f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764372978738447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=B0tK10%2FsQZcXJNXQLbUegPBwm0NM%2BnsWm%2FO4ZToun44%3D&reserved=0> and copy the link after pasting and paste it here. Crash report can be found in your crash-reports folder located in your Minecraft instance folder.
Latest log can be found in latest.log file in your logs folder.

Details
Please fill out the blanks below:
Modpack Version: ( )
Did you add or remove mods? ( )
Did you edit any config or script? ( )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.] ( )
Singleplayer, LAN game or server pack? ( )

Additional context
Add any other context about the problem here.
minecraft-exported-logs-2021-12-30T13-01-04.log<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTCreopargh%2FGreedyCraft%2Ffiles%2F7791549%2Fminecraft-exported-logs-2021-12-30T13-01-04.log&data=04%7C01%7C%7Ca874096209434d26527608d9cb51747f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764372978738447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Bo%2FHXEmOt1xevXgFt46xodDp1nnvPWp3U%2FjmN1cPBtI%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTCreopargh%2FGreedyCraft%2Fissues%2F240&data=04%7C01%7C%7Ca874096209434d26527608d9cb51747f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764372978738447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0s3cNODuYRXXk7yVZGljSO1zvTOXuP0myWQpZUg%2FQ0c%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAD6CRSGBGQ3VAZSPG7PY543UTPRS5ANCNFSM5K7CW53A&data=04%7C01%7C%7Ca874096209434d26527608d9cb51747f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764372978738447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p7PuH2%2BBrTT5LhyPR4plB4FTQwro8ViiD7JU70MvkWc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca874096209434d26527608d9cb51747f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764372978738447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=z9UU0%2BvG%2FWcciUKHYNMAoR3ryxOfNod7r9mOyUmh%2FQ8%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca874096209434d26527608d9cb51747f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764372978738447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=py5N8JWelmC7Aj5Y6N%2BOd3OChkVFk0OV%2BMRceKHkObU%3D&reserved=0>.

**Comment by TCreopargh** [comment]
内存不足
